---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{.Values.cluster_name}}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    version: null
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: 0.22.1
    values: |
      serviceCIDR: "{{.Values.serviceCIDR}}"
      service:
        type: {{.Values.service.type }}
        {{- /* Security is IMPORTANT! Be sure to set one of these values! */}}
        {{- with .Values.service.loadBalancerSourceRanges }}
        loadBalancerSourceRanges:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- /* Easier to pass a comma delimited list from an ApplicationSet's Helm values setting */}}
        {{- if .Values.service.loadBalancerSourceRangesString }}
        {{- $parts := splitList "," .Values.service.loadBalancerSourceRangesString }}
        loadBalancerSourceRanges:
          {{- range $f := $parts }}
          - "{{ $f }}"
          {{- end }}
        {{- end }}
  kubernetesVersion: "{{.Values.kubernetes_version}}"
