---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{.Values.cluster_name}}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    version: null
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: 0.22.1
  kubernetesVersion: "{{.Values.kubernetes_version}}"
